#!/usr/bin/env bash

#-- Injects cunthook into the process "Team Fortress 2" using the
#-- .so (Dynamic Library) to let you use it in game.

BINARY=$(find Project/ -name "cunthook.so" -print);
FILE="/tmp/.gl$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 6)";

if [ ! $(id -u) -eq 0 ]; then
    echo -e "Please use \"sudo\" or the inject script will not work";
    exit 1;
fi

function InjectSO() {
    [[ ! -z "$SUDO_USER" ]] && RUNUSER="$SUDO_USER" || RUNUSER="$LOGNAME";
    CMD="sudo -u $RUNUSER";
    line=$(pgrep -u $RUNUSER -o hl2_linux);
    arr=($line);

    if [ $# == 1 ]; then
        proc=$1;
    else
        if [ ${#line} == 0 ]; then
            echo -e "Please run \"Team Fortress 2\" before injecting or it will not work";
            exit 1;
        fi
        proc=${line}
    fi

    cp "$BINARY" "$FILE";

    "./Project/gdbbin" -n -q -batch \
    -ex "attach $proc" \
    -ex "call ((void*(*)(const char*, int))dlopen)(\"$FILE\", 1)" \
    -ex "call ((char*(*)(void))dlerror)()" \
    -ex "detach" \
    -ex "quit" 2> /dev/null;

    rm $FILE;

    echo -e "\nFinished injecting";
}


if [ ! -e "$BINARY" ]; then
    echo -e "Please run \"./update\" since you do not have \"cunthook.so\" within cunthook";
    exit 1;
else
    InjectSO;
fi